server:
  port: 8081

spring:
  application:
    name: patient-service

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: false

  jackson:
    default-property-inclusion: non_null

app:
  pagination:
    default-page-size: 10
    max-page-size: 100

logging:
  level:
    com.example.patient: INFO
