server:
  port: 8081

spring:
  application:
    name: patient-service

  datasource:
    url: "NOT_FOUND"
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: false

  jackson:
    default-property-inclusion: non_null

logging:
  level:
    com.example.patient: INFO
