FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn -q -B dependency:go-offline || true
COPY src ./src
RUN mvn -q -B clean package -DskipTests

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/target/patient-service-0.0.1.jar app.jar
COPY build.sh build.sh
EXPOSE 8081
ENTRYPOINT ["./build.sh"]